In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf


In [3]:
import sys
print(sys.version)



3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)]


In [4]:
#!pip install tensorflow

In [5]:
dataset = pd.read_csv('Churn_Modelling.csv')

In [6]:
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [7]:
X = dataset.drop('Exited',axis=1)
y = dataset['Exited']

In [8]:
X

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  
0           101348.88  
1           112542.58  
2           113931.57  
3            93826.63  
4            79084.10  
...               ...  
9995         96270.64  
9996        101699.77  
9997         42085.58  
9998         92888.52  
9999         38190.78  

[10000 rows x 13 columns]

In [9]:
from sklearn.preprocessing import LabelEncoder


In [10]:
le = LabelEncoder()

In [11]:
X['Gender'] = le.fit_transform(X['Gender'])

In [12]:
X

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France       0   42   
1             2    15647311       Hill          608     Spain       0   41   
2             3    15619304       Onio          502    France       0   42   
3             4    15701354       Boni          699    France       0   39   
4             5    15737888   Mitchell          850     Spain       0   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France       1   39   
9996       9997    15569892  Johnstone          516    France       1   35   
9997       9998    15584532        Liu          709    France       0   36   
9998       9999    15682355  Sabbatini          772   Germany       1   42   
9999      10000    15628319     Walker          792    France       0   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  
0           101348.88  
1           112542.58  
2           113931.57  
3            93826.63  
4            79084.10  
...               ...  
9995         96270.64  
9996        101699.77  
9997         42085.58  
9998         92888.52  
9999         38190.78  

[10000 rows x 13 columns]

In [13]:
pd.get_dummies(X['Geography'])

France  Germany  Spain
0       True    False  False
1      False    False   True
2       True    False  False
3       True    False  False
4      False    False   True
...      ...      ...    ...
9995    True    False  False
9996    True    False  False
9997    True    False  False
9998   False     True  False
9999    True    False  False

[10000 rows x 3 columns]

In [14]:
X = pd.concat([X,pd.get_dummies(X['Geography'])],axis = 1 )

In [15]:
X.drop('Geography',axis = 1,inplace=True)

In [16]:
X = X.drop(['RowNumber','CustomerId','Surname'],axis = 1)

In [17]:
X

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619       0   42       2       0.00              1          1   
1             608       0   41       1   83807.86              1          0   
2             502       0   42       8  159660.80              3          1   
3             699       0   39       1       0.00              2          0   
4             850       0   43       2  125510.82              1          1   
...           ...     ...  ...     ...        ...            ...        ...   
9995          771       1   39       5       0.00              2          1   
9996          516       1   35      10   57369.61              1          1   
9997          709       0   36       7       0.00              1          0   
9998          772       1   42       3   75075.31              2          1   
9999          792       0   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  France  Germany  Spain  
0                  1        101348.88    True    False  False  
1                  1        112542.58   False    False   True  
2                  0        113931.57    True    False  False  
3                  0         93826.63    True    False  False  
4                  1         79084.10   False    False   True  
...              ...              ...     ...      ...    ...  
9995               0         96270.64    True    False  False  
9996               1        101699.77    True    False  False  
9997               1         42085.58    True    False  False  
9998               0         92888.52   False     True  False  
9999               0         38190.78    True    False  False  

[10000 rows x 12 columns]

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size= 0.2,random_state=42)

In [20]:
from sklearn.preprocessing import StandardScaler

In [21]:
sc = StandardScaler()

In [22]:
X_train = sc.fit_transform(X_train)

In [23]:
X_train[0]

array([ 0.35649971,  0.91324755, -0.6557859 ,  0.34567966, -1.21847056,
        0.80843615,  0.64920267,  0.97481699,  1.36766974,  1.00150113,
       -0.57946723, -0.57638802])

In [24]:
X_test = sc.transform(X_test)

In [25]:
#!pip install keras

In [26]:
from tensorflow import keras

In [27]:
ann = tf.keras.models.Sequential() #Initializing the ANN

In [28]:
#Adding the input layer and the first hidden layer

In [29]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [30]:
#Adding the output layer

In [31]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [32]:
# Compiling the ANN

In [33]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [34]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100


250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.6580 - loss: 0.6309
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7829 - loss: 0.5017
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7969 - loss: 0.4627
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8051 - loss: 0.4468
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8083 - loss: 0.4313
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8152 - loss: 0.4305
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8238 - loss: 0.4143
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8220 - loss: 0.4177
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8228 - loss: 0.4217
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8292 - loss: 0.4047
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8270 - loss: 0.4013
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

In [35]:
X

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619       0   42       2       0.00              1          1   
1             608       0   41       1   83807.86              1          0   
2             502       0   42       8  159660.80              3          1   
3             699       0   39       1       0.00              2          0   
4             850       0   43       2  125510.82              1          1   
...           ...     ...  ...     ...        ...            ...        ...   
9995          771       1   39       5       0.00              2          1   
9996          516       1   35      10   57369.61              1          1   
9997          709       0   36       7       0.00              1          0   
9998          772       1   42       3   75075.31              2          1   
9999          792       0   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  France  Germany  Spain  
0                  1        101348.88    True    False  False  
1                  1        112542.58   False    False   True  
2                  0        113931.57    True    False  False  
3                  0         93826.63    True    False  False  
4                  1         79084.10   False    False   True  
...              ...              ...     ...      ...    ...  
9995               0         96270.64    True    False  False  
9996               1        101699.77    True    False  False  
9997               1         42085.58    True    False  False  
9998               0         92888.52   False     True  False  
9999               0         38190.78    True    False  False  

[10000 rows x 12 columns]

In [36]:
print(ann.predict(sc.transform([[600, 1, 40, 3, 60000, 2, 1, 1, 50000,1 ,0 ,0]]))> 0.5)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step
[[False]]


c:\Users\sayed\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [37]:
y_pred = ann.predict(X_test)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step 


In [38]:
y_pred

array([[0.02859044],
       [0.02399163],
       [0.14991178],
       ...,
       [0.6589591 ],
       [0.10355633],
       [0.2925069 ]], dtype=float32)

In [39]:
y_pred = (y_pred > 0.5)

In [40]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1553   54]
 [ 221  172]]


0.8625

In [41]:
y_pred_train = ann.predict(X_train)
y_pred_train

250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 794us/step


array([[0.00562013],
       [0.06887818],
       [0.04079065],
       ...,
       [0.7727741 ],
       [0.22158773],
       [0.5052148 ]], dtype=float32)

In [42]:
y_pred_train = (y_pred_train > 0.5)

In [43]:
accuracy_score(y_train, y_pred_train)

0.862375